// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: iceberg/proto/records_ingest.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IcebergPayload_PayloadType int32

const (
	IcebergPayload_RECORDS              IcebergPayload_PayloadType = 0
	IcebergPayload_COMMIT               IcebergPayload_PayloadType = 1
	IcebergPayload_EVOLVE_SCHEMA        IcebergPayload_PayloadType = 2
	IcebergPayload_DROP_TABLE           IcebergPayload_PayloadType = 3
	IcebergPayload_GET_OR_CREATE_TABLE  IcebergPayload_PayloadType = 4
	IcebergPayload_REFRESH_TABLE_SCHEMA IcebergPayload_PayloadType = 5
)

// Enum value maps for IcebergPayload_PayloadType.
var (
	IcebergPayload_PayloadType_name = map[int32]string{
		0: "RECORDS",
		1: "COMMIT",
		2: "EVOLVE_SCHEMA",
		3: "DROP_TABLE",
		4: "GET_OR_CREATE_TABLE",
		5: "REFRESH_TABLE_SCHEMA",
	}
	IcebergPayload_PayloadType_value = map[string]int32{
		"RECORDS":              0,
		"COMMIT":               1,
		"EVOLVE_SCHEMA":        2,
		"DROP_TABLE":           3,
		"GET_OR_CREATE_TABLE":  4,
		"REFRESH_TABLE_SCHEMA": 5,
	}
)

func (x IcebergPayload_PayloadType) Enum() *IcebergPayload_PayloadType {
	p := new(IcebergPayload_PayloadType)
	*p = x
	return p
}

func (x IcebergPayload_PayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IcebergPayload_PayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_iceberg_proto_records_ingest_proto_enumTypes[0].Descriptor()
}

func (IcebergPayload_PayloadType) Type() protoreflect.EnumType {
	return &file_iceberg_proto_records_ingest_proto_enumTypes[0]
}

func (x IcebergPayload_PayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IcebergPayload_PayloadType.Descriptor instead.
func (IcebergPayload_PayloadType) EnumDescriptor() ([]byte, []int) {
	return file_iceberg_proto_records_ingest_proto_rawDescGZIP(), []int{0, 0}
}

type IcebergPayload struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          IcebergPayload_PayloadType  `protobuf:"varint,1,opt,name=type,proto3,enum=io.debezium.server.iceberg.rpc.IcebergPayload_PayloadType" json:"type,omitempty"`
	Metadata      *IcebergPayload_Metadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Records       []*IcebergPayload_IceRecord `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload) Reset() {
	*x = IcebergPayload{}
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload) ProtoMessage() {}

func (x *IcebergPayload) ProtoReflect() protoreflect.Message {
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload.ProtoReflect.Descriptor instead.
func (*IcebergPayload) Descriptor() ([]byte, []int) {
	return file_iceberg_proto_records_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IcebergPayload) GetType() IcebergPayload_PayloadType {
	if x != nil {
		return x.Type
	}
	return IcebergPayload_RECORDS
}

func (x *IcebergPayload) GetMetadata() *IcebergPayload_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IcebergPayload) GetRecords() []*IcebergPayload_IceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type RecordIngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // Adding success boolean for better error handling
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordIngestResponse) Reset() {
	*x = RecordIngestResponse{}
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordIngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordIngestResponse) ProtoMessage() {}

func (x *RecordIngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordIngestResponse.ProtoReflect.Descriptor instead.
func (*RecordIngestResponse) Descriptor() ([]byte, []int) {
	return file_iceberg_proto_records_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *RecordIngestResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RecordIngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IcebergPayload_Metadata struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	DestTableName   string                        `protobuf:"bytes,1,opt,name=dest_table_name,json=destTableName,proto3" json:"dest_table_name,omitempty"`
	ThreadId        string                        `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	IdentifierField *string                       `protobuf:"bytes,3,opt,name=identifier_field,json=identifierField,proto3,oneof" json:"identifier_field,omitempty"`
	Schema          []*IcebergPayload_SchemaField `protobuf:"bytes,4,rep,name=schema,proto3" json:"schema,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IcebergPayload_Metadata) Reset() {
	*x = IcebergPayload_Metadata{}
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_Metadata) ProtoMessage() {}

func (x *IcebergPayload_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_Metadata.ProtoReflect.Descriptor instead.
func (*IcebergPayload_Metadata) Descriptor() ([]byte, []int) {
	return file_iceberg_proto_records_ingest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *IcebergPayload_Metadata) GetDestTableName() string {
	if x != nil {
		return x.DestTableName
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetIdentifierField() string {
	if x != nil && x.IdentifierField != nil {
		return *x.IdentifierField
	}
	return ""
}

func (x *IcebergPayload_Metadata) GetSchema() []*IcebergPayload_SchemaField {
	if x != nil {
		return x.Schema
	}
	return nil
}

type IcebergPayload_SchemaField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IceType       string                 `protobuf:"bytes,1,opt,name=ice_type,json=iceType,proto3" json:"ice_type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_SchemaField) Reset() {
	*x = IcebergPayload_SchemaField{}
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_SchemaField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_SchemaField) ProtoMessage() {}

func (x *IcebergPayload_SchemaField) ProtoReflect() protoreflect.Message {
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_SchemaField.ProtoReflect.Descriptor instead.
func (*IcebergPayload_SchemaField) Descriptor() ([]byte, []int) {
	return file_iceberg_proto_records_ingest_proto_rawDescGZIP(), []int{0, 1}
}

func (x *IcebergPayload_SchemaField) GetIceType() string {
	if x != nil {
		return x.IceType
	}
	return ""
}

func (x *IcebergPayload_SchemaField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// OPTIMIZED: Replace google.protobuf.Value with typed fields
type IcebergPayload_IceRecord struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Fields        []*IcebergPayload_IceRecord_FieldValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	RecordType    string                                 `protobuf:"bytes,2,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"` // "u", "c", "r"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_IceRecord) Reset() {
	*x = IcebergPayload_IceRecord{}
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_IceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_IceRecord) ProtoMessage() {}

func (x *IcebergPayload_IceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_IceRecord.ProtoReflect.Descriptor instead.
func (*IcebergPayload_IceRecord) Descriptor() ([]byte, []int) {
	return file_iceberg_proto_records_ingest_proto_rawDescGZIP(), []int{0, 2}
}

func (x *IcebergPayload_IceRecord) GetFields() []*IcebergPayload_IceRecord_FieldValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *IcebergPayload_IceRecord) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

// Use oneof for efficient memory usage - only one field type active per record field
type IcebergPayload_IceRecord_FieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*IcebergPayload_IceRecord_FieldValue_StringValue
	//	*IcebergPayload_IceRecord_FieldValue_IntValue
	//	*IcebergPayload_IceRecord_FieldValue_LongValue
	//	*IcebergPayload_IceRecord_FieldValue_FloatValue
	//	*IcebergPayload_IceRecord_FieldValue_DoubleValue
	//	*IcebergPayload_IceRecord_FieldValue_BoolValue
	//	*IcebergPayload_IceRecord_FieldValue_BytesValue
	Value         isIcebergPayload_IceRecord_FieldValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IcebergPayload_IceRecord_FieldValue) Reset() {
	*x = IcebergPayload_IceRecord_FieldValue{}
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IcebergPayload_IceRecord_FieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IcebergPayload_IceRecord_FieldValue) ProtoMessage() {}

func (x *IcebergPayload_IceRecord_FieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_iceberg_proto_records_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IcebergPayload_IceRecord_FieldValue.ProtoReflect.Descriptor instead.
func (*IcebergPayload_IceRecord_FieldValue) Descriptor() ([]byte, []int) {
	return file_iceberg_proto_records_ingest_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *IcebergPayload_IceRecord_FieldValue) GetValue() isIcebergPayload_IceRecord_FieldValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *IcebergPayload_IceRecord_FieldValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *IcebergPayload_IceRecord_FieldValue) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *IcebergPayload_IceRecord_FieldValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *IcebergPayload_IceRecord_FieldValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*IcebergPayload_IceRecord_FieldValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isIcebergPayload_IceRecord_FieldValue_Value interface {
	isIcebergPayload_IceRecord_FieldValue_Value()
}

type IcebergPayload_IceRecord_FieldValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_IntValue struct {
	IntValue int32 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=long_value,json=longValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type IcebergPayload_IceRecord_FieldValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*IcebergPayload_IceRecord_FieldValue_StringValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_IntValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_LongValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_FloatValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_DoubleValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

func (*IcebergPayload_IceRecord_FieldValue_BoolValue) isIcebergPayload_IceRecord_FieldValue_Value() {}

func (*IcebergPayload_IceRecord_FieldValue_BytesValue) isIcebergPayload_IceRecord_FieldValue_Value() {
}

var File_iceberg_proto_records_ingest_proto protoreflect.FileDescriptor

var file_iceberg_proto_records_ingest_proto_rawDesc = string([]byte{
	0x0a, 0x22, 0x69, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x62, 0x65, 0x7a, 0x69, 0x75,
	0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x69, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67,
	0x2e, 0x72, 0x70, 0x63, 0x22, 0xc3, 0x08, 0x0a, 0x0e, 0x49, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x62, 0x65, 0x7a,
	0x69, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x69, 0x63, 0x65, 0x62, 0x65,
	0x72, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x69, 0x6f, 0x2e, 0x64,
	0x65, 0x62, 0x65, 0x7a, 0x69, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x69,
	0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x63, 0x65, 0x62, 0x65,
	0x72, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x52, 0x0a, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e,
	0x69, 0x6f, 0x2e, 0x64, 0x65, 0x62, 0x65, 0x7a, 0x69, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x69, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49,
	0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x49, 0x63,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x1a, 0xe8, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a,
	0x0f, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x49, 0x64, 0x12, 0x2e, 0x0a, 0x10, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x52, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x62, 0x65, 0x7a, 0x69, 0x75, 0x6d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x69, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x49, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x3a, 0x0a, 0x0b, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x1a, 0x92, 0x03, 0x0a, 0x09, 0x49, 0x63, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x5b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x43, 0x2e, 0x69, 0x6f, 0x2e, 0x64, 0x65, 0x62, 0x65, 0x7a,
	0x69, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x69, 0x63, 0x65, 0x62, 0x65,
	0x72, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x49, 0x63, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x1a, 0x86, 0x02, 0x0a, 0x0a, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x7c, 0x0a, 0x0b,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x45, 0x43, 0x4f, 0x52, 0x44, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d,
	0x49, 0x54, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x56, 0x4f, 0x4c, 0x56, 0x45, 0x5f, 0x53,
	0x43, 0x48, 0x45, 0x4d, 0x41, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x52, 0x4f, 0x50, 0x5f,
	0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x47, 0x45, 0x54, 0x5f, 0x4f,
	0x52, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x04,
	0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x46, 0x52, 0x45, 0x53, 0x48, 0x5f, 0x54, 0x41, 0x42, 0x4c,
	0x45, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x41, 0x10, 0x05, 0x22, 0x48, 0x0a, 0x14, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x32, 0x8a, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49,
	0x6e, 0x67, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x0b,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x2e, 0x2e, 0x69, 0x6f,
	0x2e, 0x64, 0x65, 0x62, 0x65, 0x7a, 0x69, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x69, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x63, 0x65,
	0x62, 0x65, 0x72, 0x67, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x34, 0x2e, 0x69, 0x6f,
	0x2e, 0x64, 0x65, 0x62, 0x65, 0x7a, 0x69, 0x75, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x69, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x69, 0x63, 0x65, 0x62, 0x65, 0x72, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_iceberg_proto_records_ingest_proto_rawDescOnce sync.Once
	file_iceberg_proto_records_ingest_proto_rawDescData []byte
)

func file_iceberg_proto_records_ingest_proto_rawDescGZIP() []byte {
	file_iceberg_proto_records_ingest_proto_rawDescOnce.Do(func() {
		file_iceberg_proto_records_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iceberg_proto_records_ingest_proto_rawDesc), len(file_iceberg_proto_records_ingest_proto_rawDesc)))
	})
	return file_iceberg_proto_records_ingest_proto_rawDescData
}

var file_iceberg_proto_records_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_iceberg_proto_records_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_iceberg_proto_records_ingest_proto_goTypes = []any{
	(IcebergPayload_PayloadType)(0),             // 0: io.debezium.server.iceberg.rpc.IcebergPayload.PayloadType
	(*IcebergPayload)(nil),                      // 1: io.debezium.server.iceberg.rpc.IcebergPayload
	(*RecordIngestResponse)(nil),                // 2: io.debezium.server.iceberg.rpc.RecordIngestResponse
	(*IcebergPayload_Metadata)(nil),             // 3: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata
	(*IcebergPayload_SchemaField)(nil),          // 4: io.debezium.server.iceberg.rpc.IcebergPayload.SchemaField
	(*IcebergPayload_IceRecord)(nil),            // 5: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord
	(*IcebergPayload_IceRecord_FieldValue)(nil), // 6: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValue
}
var file_iceberg_proto_records_ingest_proto_depIdxs = []int32{
	0, // 0: io.debezium.server.iceberg.rpc.IcebergPayload.type:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.PayloadType
	3, // 1: io.debezium.server.iceberg.rpc.IcebergPayload.metadata:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.Metadata
	5, // 2: io.debezium.server.iceberg.rpc.IcebergPayload.records:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord
	4, // 3: io.debezium.server.iceberg.rpc.IcebergPayload.Metadata.schema:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.SchemaField
	6, // 4: io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.fields:type_name -> io.debezium.server.iceberg.rpc.IcebergPayload.IceRecord.FieldValue
	1, // 5: io.debezium.server.iceberg.rpc.RecordIngestService.SendRecords:input_type -> io.debezium.server.iceberg.rpc.IcebergPayload
	2, // 6: io.debezium.server.iceberg.rpc.RecordIngestService.SendRecords:output_type -> io.debezium.server.iceberg.rpc.RecordIngestResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_iceberg_proto_records_ingest_proto_init() }
func file_iceberg_proto_records_ingest_proto_init() {
	if File_iceberg_proto_records_ingest_proto != nil {
		return
	}
	file_iceberg_proto_records_ingest_proto_msgTypes[2].OneofWrappers = []any{}
	file_iceberg_proto_records_ingest_proto_msgTypes[5].OneofWrappers = []any{
		(*IcebergPayload_IceRecord_FieldValue_StringValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_IntValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_LongValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_FloatValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_DoubleValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_BoolValue)(nil),
		(*IcebergPayload_IceRecord_FieldValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iceberg_proto_records_ingest_proto_rawDesc), len(file_iceberg_proto_records_ingest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iceberg_proto_records_ingest_proto_goTypes,
		DependencyIndexes: file_iceberg_proto_records_ingest_proto_depIdxs,
		EnumInfos:         file_iceberg_proto_records_ingest_proto_enumTypes,
		MessageInfos:      file_iceberg_proto_records_ingest_proto_msgTypes,
	}.Build()
	File_iceberg_proto_records_ingest_proto = out.File
	file_iceberg_proto_records_ingest_proto_goTypes = nil
	file_iceberg_proto_records_ingest_proto_depIdxs = nil
}
