name: Performance Tests
on:
  push:
    branches:
    - "master"
    paths:
    - '**/*.go'
    - '**/*.java'
  pull_request:
    branches:
    - "*"
    paths:
    - '**/*.go'
    - '**/*.java'
  workflow_dispatch:


jobs:
  performance-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver: [ mongodb ]
        include:
        # - driver: mysql
        #   test_name: TestMySQLPerformance
        # - driver: postgres
        #   test_name: TestPostgresPerformance
        # - driver: oracle
        #   test_name: TestOraclePerformance
        - driver: mongodb
          test_name: TestMongodbPerformance

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Set up Java for Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'



    # - name: Wait for MySQL
    #   uses: nick-fields/retry@v2
    #   with:
    #     timeout_minutes: 5
    #     max_attempts: 30
    #     retry_wait_seconds: 5
    #     command: |
    #       docker exec olake_mysql-test mysql -h localhost -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SELECT 1"

    # - name: Wait for PostgreSQL
    #   uses: nick-fields/retry@v2
    #   with:
    #     timeout_minutes: 5
    #     max_attempts: 30
    #     retry_wait_seconds: 5
    #     command: |
    #       docker exec olake_postgres-test psql -h localhost -U postgres -d postgres -c "SELECT 1"



    - name: Install Go Dependencies
      run: go mod download

    - name: Build Project
      run: |
       packages=$(go list ./... | grep -v '/destination/iceberg/local-test')
       go build -v $packages

    - name: Start Test Infrastructure
      run: |
        docker compose -f ./destination/iceberg/local-test/docker-compose.yml up -d

    - name: Set up Data Directories
      run: |
        sudo mkdir -p /home/runner/work/olake-vishal/olake-vishal/destination/iceberg/local-test/data/postgres-data
        sudo mkdir -p /home/runner/work/olake-vishal/olake-vishal/destination/iceberg/local-test/data/minio-data
        sudo mkdir -p /home/runner/work/olake-vishal/olake-vishal/destination/iceberg/local-test/data/ivy-cache
        sudo chown -R 999:999 /home/runner/work/olake-vishal/olake-vishal/destination/iceberg/local-test/data
        sudo chmod -R 777 /home/runner/work/olake-vishal/olake-vishal/destination/iceberg/local-test/data

    - name: Build Iceberg Sink
      working-directory: ./destination/iceberg/olake-iceberg-java-writer
      run: mvn clean package -DskipTests


    - name: Create testconfig directories
      run: |
        mkdir -p ./drivers/${{ matrix.driver }}/internal/testconfig

    - name: Create source.json from secrets
      run: |
        echo '${{ secrets.MONGODB_SOURCE_JSON }}' > ./drivers/mongodb/internal/testconfig/source.json

    - name: Create destination.json from secrets
      run: |
        echo '${{ secrets.DESTINATION_JSON }}' > ./drivers/${{ matrix.driver }}/internal/testconfig/destination.json

    - name: Create benchmark files
      run: |
        echo '${{ secrets.BENCHMARK_JSON }}' > ./drivers/${{ matrix.driver }}/internal/testconfig/benchmark.json
        echo '${{ secrets.BENCHMARK_CDC_JSON }}' > ./drivers/${{ matrix.driver }}/internal/testconfig/benchmark_cdc.json

    - name: Run Performance Test for ${{ matrix.driver }}
      run: |
        cd ./drivers/${{ matrix.driver }}/internal
        go test -v -run ${{ matrix.test_name }}

    - name: Cleanup
      if: always()
      run: |
        docker compose -f ./destination/iceberg/local-test/docker-compose.yml down
        docker compose -f ./drivers/mysql/docker-compose.yml down
        docker compose -f ./drivers/postgres/docker-compose.yml down
